services:
  postgres:
    image: postgres:17-alpine
    container_name: easy-order-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: easy_order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - easy-order-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d easy_order"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easy-order-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - easy-order-network
    entrypoint: ["/usr/src/app/docker-entrypoint.sh"]

volumes:
  postgres_data:

networks:
  easy-order-network:
    driver: bridge 